[package]
name = "rust-style"
version = "0.0.1"
authors = ["Seth Pink <sethpink@gmail.com>", "Matthias Tellen <matthias.tellen@gmail.com>"]
license = "MIT"

[dependencies]
docopt = "*"
glob = "*"
rustc-serialize = "*"
syntex_syntax = "*"
typed-arena = "*"
toml = "*"
diff = "*"
